name: Build Qhora-301w Images
on: [push]

jobs:
    build:
        name: Prepare and build Qhora-301w images
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Download qhora301 files
              run: |
                wget https://github.com/FixedBit/qhora301w-files/releases/download/original/qhora301w-files.tar.gz
                mkdir files
                tar xvfz qhora301w-files.tar.gz -C ./files

            - name: Update and install feeds
              run: |
                ./scripts/feeds update -a
                ./scripts/feeds install -a

            - name: Generate config for Qhora-301w
              run: |
                echo "CONFIG_TARGET_ipq807x=y" > .config
                echo "CONFIG_TARGET_ipq807x_generic=y\n" >> .config
                echo "CONFIG_TARGET_MULTI_PROFILE=n\n" >> .config
                echo "CONFIG_TARGET_ALL_PROFILES=n\n" >> .config
                echo "CONFIG_TARGET_ipq807x_generic_DEVICE_qnap_301w=y" >> .config
                echo "CONFIG_TARGET_PER_DEVICE_ROOTFS=y\n" >> .config
                echo "CONFIG_TARGET_ROOTFS_INITRAMFS=y\n" >> .config
                echo "CONFIG_TARGET_INITRAMFS_COMPRESSION_ZSTD=y\n" >> .config
                echo "CONFIG_PACKAGE_luci=y\n" >> .config
                echo "CONFIG_PACKAGE_luci-ssl=y\n" >> .config
                echo "CONFIG_PACKAGE_kmod-qca-nss-drv=y\n" >> .config
                echo "CONFIG_PACKAGE_qca-ssdk-shell=y\n" >> .config
                echo "CONFIG_PACKAGE_aq-fw-download=y\n" >> .config
                echo "CONFIG_PACKAGE_nano=y\n" >> .config
                echo "CONFIG_PACKAGE_luci-app-sqm=y\n" >> .config
                make defconfig

            - name: Download package sources
              run: make download V=s

            - name: Build tools
              run: |
                make tools/install -j$(nproc) V=s || \
                make tools/install V=s

            - name: Build toolchain
              run: |
                make toolchain/install -j$(nproc) V=s || \
                make toolchain/install V=s

            - name: Build target images
              run: |
                make -j$(nproc) V=s || \
                make V=s

            - name: TAR output
              run: tar -cvf qhora301w-images.tar bin/targets/ipq807x/generic

            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                name: qhora301w-images
                path: qhora301w-images.tar

    release:
          name: Make a release
          runs-on: ubuntu-latest
          needs: build

          steps:
            - name: Download the image artifacts
              uses: actions/download-artifact@v2
              with:
                name: qhora301w-images

            - name: Extract the image artifacts
              run: tar xf qhora301w-images.tar

            - name: Get the current date
              run: echo "NOW=$(date +%F)" >> $GITHUB_ENV

            - name: Create a release
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                prerelease: true
                title: "Updated Qhora-301w prebuilt images ${{ env.NOW }}"
                automatic_release_tag: "ipq807x-qhora301w-${{ env.NOW }}"
                files: bin/targets/ipq807x/generic/*
